# Lint対象から除外するパス
excluded:
    - Carthage
    - Pods
    - covid-19-graphTests
    - covid-19-graphUITests
    - CoreTests
    - Core/API/Response
    - R.generated.swift
    - covid-19-graph/Resource

opt_in_rules:
#    - force_unwrapping
    
variable_name:
    min_length:
        warning: 2
        error: 2
    excluded:
    - URLRequest
    - URLResponse
    
function_body_length:
    warning: 100
#    error: 150

type_body_length:
    warning: 400
#   error: 600
    
file_length:
    warning: 500
#    error: 1000
    
force_cast: warning

disabled_rules:
    - line_length
    - trailing_whitespace
